// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import('../components/Footer.vue')['default'],
    'Menu': typeof import('../components/Menu.vue')['default'],
    'Section': typeof import('../components/Section.vue')['default'],
    'Card': typeof import('../components/card.vue')['default'],
    'Content': typeof import('../components/content.vue')['default'],
    'ContentsSections': typeof import('../components/contents-sections.vue')['default'],
    'Example': typeof import('../components/example.vue')['default'],
    'FacebookIcon': typeof import('../components/facebook-icon.vue')['default'],
    'GetStarted': typeof import('../components/get-started.vue')['default'],
    'GithubIcon': typeof import('../components/github-icon.vue')['default'],
    'HeaderIndex': typeof import('../components/header-index.vue')['default'],
    'InstagramIcon': typeof import('../components/instagram-icon.vue')['default'],
    'Navbar': typeof import('../components/navbar.vue')['default'],
    'Services': typeof import('../components/services.vue')['default'],
    'TwitterIcon': typeof import('../components/twitter-icon.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
